project:
  type: book
  output-dir: docs

book:
  title: "Muhammad Rafi Dhiyaulhaq"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18222069 Muhammad Rafi Dhiyaulhaq"
  date: "15 September 2025"
  chapters:
    - index.qmd
    - intro.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - My_Concepts/index.qmd
    - My_Opinions/index.qmd
    - My_Innovations/index.qmd
    - My_Knowledge/index.qmd
    - My_Professional_Reviews/index.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true